In [1]:
import kaggle
!kaggle datasets download -d kazanova/sentiment140

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /Users/mahemasingh/.kaggle/kaggle.json'
Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /Users/mahemasingh/.kaggle/kaggle.json'
Downloading sentiment140.zip to /Users/mahemasingh/twitter-sentiment-analysis
100%|██████████████████████████████████████| 80.9M/80.9M [00:04<00:00, 17.4MB/s]
100%|██████████████████████████████████████| 80.9M/80.9M [00:04<00:00, 18.7MB/s]

In [2]:
from zipfile import ZipFile
file_name = 'sentiment140.zip'
with ZipFile(file_name, 'r') as zip:
  zip.extractall()
  print('Done extracting Zip file')

Done extracting Zip file

In [9]:
import pandas as pd
# this dataset needs an encoding set + doesn't read headers in the csv version, we have to add
data = pd.read_csv('training.1600000.processed.noemoticon.csv', encoding = "ISO-8859-1", header=None)
data.columns = ['polarity', 'id', 'date', 'flag','user','tweet']

In [10]:
# TODO: I think the only columns we want are id, date, user??, and tweet
trimmed_data = data[['id', 'date', 'user', 'tweet']]

In [11]:
trimmed_data.head(20)

,id,date,user,tweet
0,1467810369,Mon Apr 06 22:19:45 PDT 2009,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,1467810672,Mon Apr 06 22:19:49 PDT 2009,scotthamilton,is upset that he can't update his Facebook by ...
2,1467810917,Mon Apr 06 22:19:53 PDT 2009,mattycus,@Kenichan I dived many times for the ball. Man...
3,1467811184,Mon Apr 06 22:19:57 PDT 2009,ElleCTF,my whole body feels itchy and like its on fire
4,1467811193,Mon Apr 06 22:19:57 PDT 2009,Karoli,"@nationwideclass no, it's not behaving at all...."
5,1467811372,Mon Apr 06 22:20:00 PDT 2009,joy_wolf,@Kwesidei not the whole crew
6,1467811592,Mon Apr 06 22:20:03 PDT 2009,mybirch,Need a hug
7,1467811594,Mon Apr 06 22:20:03 PDT 2009,coZZ,@LOLTrish hey long time no see! Yes.. Rains a...
8,1467811795,Mon Apr 06 22:20:05 PDT 2009,2Hood4Hollywood,@Tatiana_K nope they didn't have it
9,1467812025,Mon Apr 06 22:20:09 PDT 2009,mimismo,@twittera que me muera ?
10,1467812416,Mon Apr 06 22:20:16 PDT 2009,erinx3leannexo,spring break in plain city... it's snowing
11,1467812579,Mon Apr 06 22:20:17 PDT 2009,pardonlauren,I just re-pierced my ears
12,1467812723,Mon Apr 06 22:20:19 PDT 2009,TLeC,@caregiving I couldn't bear to watch it. And ...
13,1467812771,Mon Apr 06 22:20:19 PDT 2009,robrobbierobert,"@octolinz16 It it counts, idk why I did either..."
14,1467812784,Mon Apr 06 22:20:20 PDT 2009,bayofwolves,"@smarrison i would've been the first, but i di..."
15,1467812799,Mon Apr 06 22:20:20 PDT 2009,HairByJess,@iamjazzyfizzle I wish I got to watch it with ...
16,1467812964,Mon Apr 06 22:20:22 PDT 2009,lovesongwriter,Hollis' death scene will hurt me severely to w...
17,1467813137,Mon Apr 06 22:20:25 PDT 2009,armotley,about to file taxes
18,1467813579,Mon Apr 06 22:20:31 PDT 2009,starkissed,@LettyA ahh ive always wanted to see rent lov...
19,1467813782,Mon Apr 06 22:20:34 PDT 2009,gi_gi_bee,@FakerPattyPattz Oh dear. Were you drinking ou...

In [16]:
#checking that none of the values are NULL
trimmed_data.isna().sum()

id       0
date     0
user     0
tweet    0
dtype: int64